### ISSUE TITLE
Suggested variable for vertical currents derived using flight models

### ISSUE THREAD

**Issue by eleanorfrajka** [OceanGlidersCommunity/OG-format-user-manual#255]
moderator: @OceanGlidersCommunity/format-maintainers

**Is this related to a specific platform models**
All platforms (as far as I'm aware), or at least Seaglider, Slocum, Seaexplorer, Spray.

**Describe the solution you'd like**
A variable to use for vertical seawater velocity derived from using a glider flight model (rather than e.g., an ADCP).  

**Additional context**
This is in the context of an effort to progress with multi-platform, multi-region investigations into vertical seawater velocity [Vertical Velocity](https://github.com/OceanGlidersCommunity/Vertical_Velocities_SOP).  In order to use OG format, we will need a variable for vertical seawater velocity which does not appear to be available.

I think the guidance was to check some places to make sure the choice of variable name doesn't clash, but I'm not sure where these were.

**Comment by emmerbodc** [comment]
Hello Eleanor. I'm adding label vocab to this issue as this sounds like we need a new OG1 parameter code. 
Please see current collection on https://vocab.nerc.ac.uk/collection/OG1/current/

Once a description has been agreed upon, a new request will need to go in at 
https://github.com/nvs-vocabs/OG1/issues to add this to the collection

FYI OG vocab team - 
@vturpin 
@fmargirier
@ptestor 
@clayton33 
@ShaoqiongYang 
@robynowen 

@eleanorfrajka Will you be able to help us with the description please

**Comment by emmerbodc** [comment]
Discussed vocab meeting 27/04/2026 
@fmargirier will create a definition for a new parameter code.

**Comment by fmargirier** [comment]
My suggestion, please let me know if that sounds reasonable @emmerbodc @callumrollo @jenseva .

ID :
WATER_VELOC_FLIGHTMODEL_W

Preferred Label :
Upward vertical velocity in the water body by glider flight model

Definition :
The vertical velocity is estimated as the difference between the velocity derived from the rate of change of pressure and that predicted by the glider flight model.

**Comment by eleanorfrajka** [comment]
Sorry--just saw this.  This is what we had been using:

```
GLIDE_ANGLE:
  long_name: glide angle from hydrodynamic model
  units: degrees
  observation_type: calculated
GLIDE_SPEED:
  long_name: glider speed from hydrodynamic model
  units: m s-1
  observation_type: calculated
GLIDER_HORZ_VELO_MODEL:
  long_name: glider_horizontal_speed_from_glider_flight_model
  standard_name: horizontal_glider_speed
  units: m s-1
  observation_type: calculated
  sensor: sensor_glider_model
  positive: east
GLIDER_VERT_VELO_MODEL:
  long_name: glider vertical speed from glider flight model
  standard_name: vertical_glider_speed
  units: m s-1
  observation_type: calculated
  sensor: sensor_glider_model
  positive: up
GLIDER_VERT_VELO_PRESSURE:
  long_name: glider vertical speed from pressure
  standard_name: vertical_glider_speed
  units: m s-1
  observation_type: calculated
  sensor: sensor_ctd
  positive: up
VERT_CURR_MODEL:
  long_name: vertical current of seawater derived from glider flight model
  standard_name: vertical_current
  units: m s-1
  observation_type: calculated
  positive: up
```

@fmargirier One suggestion I'd make is to specify the direction of subtraction (velocity from the rate of change of pressure minus velocity predicted by the glider flight model).
